name: Continuous integration for backend

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch'
        required: true
        default: 'main'
        type: string
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkingout code
        uses: actions/checkout@v3

      - name: Setting up the Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'

      - name: Installing the pipenv
        run: |
          cd starter/backend  
          pip install pipenv
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Installing the dependencies
        run: |
          cd starter/backend
          pipenv install --dev

      - name: Running the lint
        run: |
          cd starter/backend
          pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'

      - name: Installng pipenv
        run: |
          cd starter/backend  
          pip install pipenv

      - name: Installing the dependencies
        run: |
          cd starter/backend 
          pipenv install

      - name: Running the tests
        run: |
          cd starter/backend 
          pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkingout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Building the docker image
        run: |
          cd starter/backend 
          docker build --tag mp-backend:latest .
      
      - name: Running the docker image
        run: docker run -p 5000:5000 --name mp-backend -d mp-backend

      - name: Checking the running application
        run: curl http://localhost:5000/movies
        
      - name: Reviewing the logs
        run: docker logs mp-backend
        
      - name: stop the application
        run: docker stop mp-backend
