name: Continuous deployment for backend
env:
      AWS_REGION: "us-east-1"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch'
        required: true
        default: 'main'
        type: string
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'

      - name: Installing the pipenv
        run: |
          cd starter/backend  
          pip install pipenv
      
      - name: Installing the dependencies
        run: |
          cd starter/backend
          pipenv install --dev

      - name: Running the lint
        run: |
          cd starter/backend
          pipenv run lint
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'

      - name: Installing the pipenv
        run: |
          cd starter/backend  
          pip install pipenv

      - name: Installing the dependencies
        run: |
          cd starter/backend 
          pipenv install

      - name: Running the tests
        run: |
          cd starter/backend 
          pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checking out  the code
        uses: actions/checkout@v3

      - name: Settig up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Configuring the AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Logging in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Building Docker image
        run: |
          cd starter/backend
          ECR_REPO=${{ secrets.ECR_REPO_URI_BACKEND }}
          GIT_SHA=${{ github.sha }}
          IMAGE_TAG="${ECR_REPO}:${GIT_SHA}"
          docker build -t $IMAGE_TAG .
      
      - name: Pushing the Docker image to ECR
        run: |
          ECR_REPO=${{ secrets.ECR_REPO_URI_BACKEND }}
          GIT_SHA=${{ github.sha }}
          IMAGE_TAG="${ECR_REPO}:${GIT_SHA}"
          docker push $IMAGE_TAG
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
 
      - name: Configure kubectl config file
        run: |
          aws eks --region us-east-1 update-kubeconfig --name cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${AWS_REGION}
      
      - name: Deploying to Kubernetes
        run: |
          cd starter/backend/k8s 
          GIT_SHA=${{ github.sha }}
          ECR_REPO=${{ secrets.ECR_REPO_URI_BACKEND }}
          IMAGE_TAG="${ECR_REPO}:${GIT_SHA}"
          kustomize edit set image backend=${IMAGE_TAG}
          kustomize build | kubectl apply -f - --validate=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${AWS_REGION}

      - name: Get services
        run: |
          kubectl get svc
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${AWS_REGION}
