name: Continuous integration for frontend

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch'
        required: true
        default: 'main'
        type: string
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkingout code
        uses: actions/checkout@v3

      - name: Setting up Node js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing the dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Running lint
        run: |
          cd starter/frontend
          npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkingout code
        uses: actions/checkout@v3

      - name: Setting up Node js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing the dependencies
        run: |
          cd starter/frontend 
          npm install

      - name: Running the tests
        run: |
          cd starter/frontend 
          npm test
  
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkingout code
        uses: actions/checkout@v3

      - name: Setting up the docker
        uses: docker/setup-buildx-action@v2

      - name: Building the docker image
        run: |
          cd starter/frontend 
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
      
      - name: Running the docker image
        run: docker run --name mp-frontend -p 3000:3000 -d mp-frontend